general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

listener {
    timeout = 180
    on-timeout = light -O -S 10
    on-resume = light -I
}

listener {
    timeout = 380
    on-timeout = hyperctl dispatch dpms off
    one-resume = hyperctl dispatch dpms on
}

listener {
    timeout = 500                            # in seconds
    on-timeout = systemctl suspend # command to run when timeout has passed
    
}